# Generated by Django 3.1.1 on 2020-09-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypod', '0002_auto_20200930_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imgCategory',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
