# Generated by Django 3.1.1 on 2020-10-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citypod', '0003_auto_20200930_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imgCategory',
            new_name='categoryImg',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subImgCategory',
            new_name='subCategoryImg',
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementName', models.CharField(max_length=50)),
                ('elementDescription', models.TextField()),
                ('elementImg', models.ImageField(blank=True, null=True, upload_to='')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='citypod.subcategory')),
            ],
        ),
    ]
