# Generated by Django 3.1.1 on 2020-10-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citypod', '0005_element_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='category',
        ),
        migrations.AddField(
            model_name='element',
            name='categoryElement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='citypod.category'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(max_length=50)),
                ('pageDescription', models.TextField()),
                ('pageFile', models.FileField(blank=True, null=True, upload_to='')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='citypod.element')),
            ],
        ),
    ]
