# Generated by Django 3.1.1 on 2020-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypod', '0006_auto_20201001_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImg',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='element',
            name='elementImg',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCategoryImg',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
