# Generated by Django 3.1.1 on 2020-10-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypod', '0007_auto_20201001_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pageFile',
            field=models.FileField(blank=True, null=True, upload_to='image'),
        ),
    ]
