# Generated by Django 3.1.1 on 2020-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypod', '0008_auto_20201009_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='citypod.Category'),
        ),
    ]
