# Generated by Django 3.1.1 on 2020-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypod', '0009_auto_20201026_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='elementImg',
            field=models.ImageField(blank=True, null=True, upload_to='./image'),
        ),
    ]
