# Generated by Django 3.1.1 on 2020-10-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypod', '0011_auto_20201026_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImg',
            field=models.ImageField(blank=True, null=True, upload_to='citypod/image/categorie'),
        ),
        migrations.RemoveField(
            model_name='element',
            name='categoryElement',
        ),
        migrations.AddField(
            model_name='element',
            name='categoryElement',
            field=models.ManyToManyField(blank=True, null=True, to='citypod.Category'),
        ),
        migrations.AlterField(
            model_name='element',
            name='elementImg',
            field=models.ImageField(blank=True, null=True, upload_to='citypod/image/element'),
        ),
        migrations.RemoveField(
            model_name='element',
            name='subCategory',
        ),
        migrations.AddField(
            model_name='element',
            name='subCategory',
            field=models.ManyToManyField(blank=True, null=True, to='citypod.SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCategoryImg',
            field=models.ImageField(blank=True, null=True, upload_to='citypod/image/subcategorie'),
        ),
    ]
